apiVersion: v1
kind: Service
metadata:
  name: capstone-ENVIRONMENT-svc-BUILD_NUMBER
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      name: http
    - name: "https"
      port: 443
      targetPort: 80
      protocol: "TCP"
  selector:
    app: capstone
    version: "BUILD_NUMBER"